name: 'support_ai_analytics'
version: '1.0.0'
config-version: 2

profile: 'support_ai_analytics'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  support_ai_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
